#!/opt/homebrew/bin/python3

import urllib.request
from bs4 import BeautifulSoup
import os
import sys

cwd = os.getcwd ()
path = os.path.realpath (__file__)
directory = os.path.dirname(path)

os.chdir (directory)

url = r'https://ziglang.org/download/'
print (url)
content = urllib.request.urlopen (url).read ()
soup = BeautifulSoup (content, 'html.parser')
for link in soup.find_all ('a'):
    url = link.get('href')
    if 'macos-aarch64-0.12' in url and url[-6:] == 'tar.xz':
        print (url)
        index = url.rfind ('/')
        filename = url[index+1:]
        partname = url[index+1:-7]
        data = urllib.request.urlopen (url).read ()
        with open(filename, 'wb') as fp:
            fp.write (data)
        print (f"{filename}")
        os.system (f"tar xf {filename}")
        os.system ("rm -rf ~/Library/zig")
        os.system ("mkdir ~/Library/zig")
        os.system (f"mv {partname}/* ~/Library/zig")
        os.system (f"rm -rf {partname}")
        os.system (f"rm -f {filename}")
        print ("")
        os.system ("zig version")
        os.system ("zig zen")
        sys.exit (0)
sys.exit (1)
